import { MenuCategory, MenuItem } from '@/types/menu';
import { StaffMember } from '@/types/staff';
import { AdminUser } from '@/types/user';
import { AuditLog } from '@/types/audit';
import { CafeSettings, WebsiteSettings } from '@/types/settings';

export const INITIAL_CATEGORIES: MenuCategory[] = [
  {
    id: 'cat-coffee',
    name: 'Artisan Coffee',
    slug: 'artisan-coffee',
    description: 'Freshly roasted specialty coffee, single-origin brews & espresso classics.',
    icon: '☕',
    displayOrder: 1,
    isActive: true,
    itemCount: 4,
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'cat-tea',
    name: 'Specialty Teas',
    slug: 'specialty-teas',
    description: 'Organic whole-leaf teas, ceremonial matcha, and calming herbal infusions.',
    icon: '🍵',
    displayOrder: 2,
    isActive: true,
    itemCount: 2,
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'cat-bakery',
    name: 'Bakery & Pastries',
    slug: 'bakery-pastries',
    description: 'Flaky croissants, sourdough toasts, artisanal muffins and brownies.',
    icon: '🥐',
    displayOrder: 3,
    isActive: true,
    itemCount: 3,
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'cat-savory',
    name: 'Savory & Brunch',
    slug: 'savory-brunch',
    description: 'Gourmet sandwiches, truffle toasts, avocado bowls and brunch platters.',
    icon: '🥪',
    displayOrder: 4,
    isActive: true,
    itemCount: 3,
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'cat-desserts',
    name: 'Desserts & Cakes',
    slug: 'desserts-cakes',
    description: 'Handcrafted cheesecakes, tiramisu cups, and warm skillet cookies.',
    icon: '🍰',
    displayOrder: 5,
    isActive: true,
    itemCount: 2,
    createdAt: '2026-01-15T08:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z',
  },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Aura Signature Caramel Macchiato',
    description: 'Fresh espresso layered with velvety steamed milk, vanilla bean syrup, and drizzled with housemade salted caramel.',
    categoryId: 'cat-coffee',
    categoryName: 'Artisan Coffee',
    price: 280,
    discountPrice: 240,
    imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isBestseller: true,
    isFeatured: true,
    isAvailable: true,
    prepTimeMinutes: 4,
    ingredients: ['Espresso (100% Arabica)', 'Whole Milk / Oat Milk', 'Madagascar Vanilla', 'Salted Caramel Drizzle'],
    allergens: ['Dairy'],
    tags: ['Signature', 'Bestseller', 'Hot/Iced'],
    displayOrder: 1,
    createdAt: '2026-01-15T09:00:00.000Z',
    updatedAt: '2026-03-02T11:30:00.000Z',
  },
  {
    id: 'item-2',
    name: 'Spanish Latte with Condensed Milk',
    description: 'Rich double espresso infused with sweetened condensed milk and silky textured whole milk.',
    categoryId: 'cat-coffee',
    categoryName: 'Artisan Coffee',
    price: 260,
    discountPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isBestseller: true,
    isFeatured: true,
    isAvailable: true,
    prepTimeMinutes: 5,
    ingredients: ['Double Espresso', 'Condensed Milk', 'Fresh Milk', 'Cinnamon Dust'],
    allergens: ['Dairy'],
    tags: ['Popular', 'Sweet'],
    displayOrder: 2,
    createdAt: '2026-01-16T10:00:00.000Z',
    updatedAt: '2026-03-02T12:00:00.000Z',
  },
  {
    id: 'item-3',
    name: 'Ceremonial Uji Matcha Latte',
    description: 'Stone-ground ceremonial grade Japanese matcha whisked to perfection with creamy oat milk.',
    categoryId: 'cat-tea',
    categoryName: 'Specialty Teas',
    price: 310,
    discountPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isBestseller: false,
    isFeatured: true,
    isAvailable: true,
    prepTimeMinutes: 4,
    ingredients: ['Uji Matcha Powder', 'Oat Milk', 'Agave Nectar'],
    allergens: [],
    tags: ['Vegan', 'Antioxidant', 'Japanese'],
    displayOrder: 3,
    createdAt: '2026-01-17T11:00:00.000Z',
    updatedAt: '2026-02-28T14:20:00.000Z',
  },
  {
    id: 'item-4',
    name: 'Artisanal Butter Croissant',
    description: 'Baked fresh every morning with French Normandy butter for 32 delicate, crisp, flaky golden layers.',
    categoryId: 'cat-bakery',
    categoryName: 'Bakery & Pastries',
    price: 180,
    discountPrice: 150,
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isBestseller: true,
    isFeatured: true,
    isAvailable: true,
    prepTimeMinutes: 2,
    ingredients: ['French Wheat Flour', 'Normandy Butter', 'Yeast', 'Sea Salt'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Fresh Daily', 'French', 'Breakfast'],
    displayOrder: 4,
    createdAt: '2026-01-18T07:30:00.000Z',
    updatedAt: '2026-03-01T08:15:00.000Z',
  },
  {
    id: 'item-5',
    name: 'Truffle Mushroom Sourdough Melt',
    description: 'Wild forest mushrooms sautéed in garlic thyme butter, melted aged Gruyère & provolone on toasted rustic sourdough.',
    categoryId: 'cat-savory',
    categoryName: 'Savory & Brunch',
    price: 360,
    discountPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isBestseller: false,
    isFeatured: true,
    isAvailable: true,
    prepTimeMinutes: 8,
    ingredients: ['Artisan Sourdough', 'Wild Mushrooms', 'Gruyère Cheese', 'White Truffle Oil'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Gourmet', 'Warm Melt'],
    displayOrder: 5,
    createdAt: '2026-01-20T12:00:00.000Z',
    updatedAt: '2026-03-03T16:00:00.000Z',
  },
  {
    id: 'item-6',
    name: 'Classic Espresso Tiramisu',
    description: 'Savoiardi ladyfingers soaked in our freshly pulled dark espresso, layered with whipped mascarpone cream and Dutch cocoa.',
    categoryId: 'cat-desserts',
    categoryName: 'Desserts & Cakes',
    price: 320,
    discountPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isBestseller: true,
    isFeatured: false,
    isAvailable: true,
    prepTimeMinutes: 3,
    ingredients: ['Mascarpone Cream', 'Cafe Aura Espresso', 'Ladyfingers', 'Dutch Cocoa'],
    allergens: ['Dairy', 'Eggs', 'Gluten'],
    tags: ['Dessert', 'Housemade'],
    displayOrder: 6,
    createdAt: '2026-01-22T14:00:00.000Z',
    updatedAt: '2026-03-01T15:45:00.000Z',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'staff-1',
    employeeId: 'AUR-001',
    fullName: 'Elena Rostova',
    email: 'elena.rostova@cafeaura.com',
    phone: '+1 (555) 234-5678',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    position: 'Head of Operations & GM',
    department: 'Management',
    role: 'super_admin',
    shift: 'Full Day',
    status: 'active',
    joiningDate: '2024-03-01',
    emergencyContact: {
      name: 'Dmitri Rostov',
      relationship: 'Spouse',
      phone: '+1 (555) 890-1234',
    },
    notes: 'Oversees whole café operational flow, vendor supply, and team excellence.',
    createdAt: '2024-03-01T08:00:00.000Z',
    updatedAt: '2026-03-01T09:00:00.000Z',
  },
  {
    id: 'staff-2',
    employeeId: 'AUR-002',
    fullName: 'Marcus Vance',
    email: 'marcus.vance@cafeaura.com',
    phone: '+1 (555) 345-6789',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    position: 'Lead Barista & Roast Master',
    department: 'Barista & Coffee',
    role: 'menu_manager',
    shift: 'Morning (6AM - 2PM)',
    status: 'active',
    joiningDate: '2024-05-15',
    emergencyContact: {
      name: 'Sarah Vance',
      relationship: 'Sister',
      phone: '+1 (555) 901-2345',
    },
    notes: 'Q-grader certified. Manages coffee recipes and roastery calibration.',
    createdAt: '2024-05-15T08:00:00.000Z',
    updatedAt: '2026-02-25T11:00:00.000Z',
  },
  {
    id: 'staff-3',
    employeeId: 'AUR-003',
    fullName: 'Chloe Dupont',
    email: 'chloe.dupont@cafeaura.com',
    phone: '+1 (555) 456-7890',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    position: 'Pastry Chef',
    department: 'Kitchen & Bakery',
    role: 'staff',
    shift: 'Morning (6AM - 2PM)',
    status: 'active',
    joiningDate: '2024-08-01',
    emergencyContact: {
      name: 'Jean Dupont',
      relationship: 'Father',
      phone: '+1 (555) 012-3456',
    },
    notes: 'Specializes in laminated doughs and seasonal cake creations.',
    createdAt: '2024-08-01T08:00:00.000Z',
    updatedAt: '2026-01-20T10:00:00.000Z',
  },
  {
    id: 'staff-4',
    employeeId: 'AUR-004',
    fullName: 'Liam Chen',
    email: 'liam.chen@cafeaura.com',
    phone: '+1 (555) 567-8901',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    position: 'Floor Manager & Host',
    department: 'Service & Front',
    role: 'manager',
    shift: 'Evening (2PM - 10PM)',
    status: 'active',
    joiningDate: '2025-01-10',
    emergencyContact: {
      name: 'Mei Chen',
      relationship: 'Mother',
      phone: '+1 (555) 123-4567',
    },
    notes: 'Handles guest reservations, event bookings, and customer satisfaction.',
    createdAt: '2025-01-10T08:00:00.000Z',
    updatedAt: '2026-02-18T16:00:00.000Z',
  },
];

export const INITIAL_USERS: AdminUser[] = [
  {
    uid: 'user-superadmin-01',
    email: 'admin@cafeaura.com',
    displayName: 'Elena Rostova (Super Admin)',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    role: 'super_admin',
    status: 'active',
    providerId: 'password',
    createdAt: '2024-01-01T00:00:00.000Z',
    lastLoginAt: '2026-09-09T14:30:00.000Z',
  },
  {
    uid: 'user-manager-02',
    email: 'liam.manager@cafeaura.com',
    displayName: 'Liam Chen (Manager)',
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    role: 'manager',
    status: 'active',
    providerId: 'google.com',
    createdAt: '2025-01-10T00:00:00.000Z',
    lastLoginAt: '2026-09-08T18:45:00.000Z',
  },
  {
    uid: 'user-menumgr-03',
    email: 'marcus.menu@cafeaura.com',
    displayName: 'Marcus Vance (Menu)',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    role: 'menu_manager',
    status: 'active',
    providerId: 'password',
    createdAt: '2024-05-15T00:00:00.000Z',
    lastLoginAt: '2026-09-07T09:12:00.000Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    userId: 'user-superadmin-01',
    userName: 'Elena Rostova',
    userEmail: 'admin@cafeaura.com',
    userRole: 'super_admin',
    action: 'MENU_UPDATE',
    resourceType: 'menu',
    resourceId: 'item-1',
    details: 'Updated price and promotional discount for Aura Signature Caramel Macchiato (₹280 -> ₹240)',
    timestamp: '2026-09-09T14:25:00.000Z',
  },
  {
    id: 'log-002',
    userId: 'user-superadmin-01',
    userName: 'Elena Rostova',
    userEmail: 'admin@cafeaura.com',
    userRole: 'super_admin',
    action: 'AUTH_LOGIN',
    resourceType: 'auth',
    details: 'Successful administrator login with Email/Password credentials',
    timestamp: '2026-09-09T14:00:00.000Z',
  },
  {
    id: 'log-003',
    userId: 'user-manager-02',
    userName: 'Liam Chen',
    userEmail: 'liam.manager@cafeaura.com',
    userRole: 'manager',
    action: 'STAFF_STATUS_CHANGE',
    resourceType: 'staff',
    resourceId: 'staff-3',
    details: 'Set staff Chloe Dupont status to Active for Morning Shift',
    timestamp: '2026-09-08T18:45:00.000Z',
  },
  {
    id: 'log-004',
    userId: 'user-superadmin-01',
    userName: 'Elena Rostova',
    userEmail: 'admin@cafeaura.com',
    userRole: 'super_admin',
    action: 'SETTINGS_UPDATE',
    resourceType: 'settings',
    details: 'Updated seasonal promotional banner text & opening hours',
    timestamp: '2026-09-07T11:20:00.000Z',
  },
];

export const INITIAL_CAFE_SETTINGS: CafeSettings = {
  cafeName: 'Cafe Aura',
  tagline: 'Freshly Brewed Specialty Coffee & Cozy Moments',
  logoUrl: '/cafe_logo.png',
  address: '108 Grand Avenue, Arts District, Seattle, WA 98101',
  phone: '+1 (555) 789-2872',
  email: 'hello@cafeaura.com',
  currency: 'USD',
  currencySymbol: '$',
  taxRatePercent: 8.5,
  openingHours: [
    { day: 'Monday', openTime: '06:30', closeTime: '21:00', isClosed: false },
    { day: 'Tuesday', openTime: '06:30', closeTime: '21:00', isClosed: false },
    { day: 'Wednesday', openTime: '06:30', closeTime: '21:00', isClosed: false },
    { day: 'Thursday', openTime: '06:30', closeTime: '21:00', isClosed: false },
    { day: 'Friday', openTime: '06:30', closeTime: '22:00', isClosed: false },
    { day: 'Saturday', openTime: '07:00', closeTime: '22:30', isClosed: false },
    { day: 'Sunday', openTime: '07:30', closeTime: '20:00', isClosed: false },
  ],
  socialLinks: {
    instagram: 'https://instagram.com/cafeaura.official',
    facebook: 'https://facebook.com/cafeauraroasters',
    twitter: 'https://twitter.com/cafeaura',
  },
};

export const INITIAL_WEBSITE_SETTINGS: WebsiteSettings = {
  bannerEnabled: true,
  bannerText: '✨ Try our Autumn Special: Salted Caramel Maple Cortado with Artisan Croissants!',
  bannerLink: '#menu',
  highlightedSpecialId: 'item-1',
  orderOnlineEnabled: true,
  tableReservationEnabled: true,
  maintenanceMode: false,
};
